# docker-compose up --build --no-cache
# docker-compose up --build --force-recreate -d scrapyrt
# cli docker exec -it b30c070f10e0 bash
# docker exec -it <container_name> psql -U<user_name> -a <db_name>
# docker exec -it <container_name> psql -U<user_name> -a <db_name> -c '<command/query>'
## docker formats
#
#The following two formats work:
#
#Format #1
#
#environment:
#  MYSQL_ROOT_PASSWORD: rootpassword
#Format #2
#
#environment:
#  - MYSQL_ROOT_PASSWORD=rootpassword

version: "3.3"

services:
  db:
    container_name: hawksense-postgres
    build:
      context: .
      dockerfile: postgres.dockerfile
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # persist data even if container shuts down
  pgadmin:
    container_name: hawksense-pgadmin
    image: dpage/pgadmin4
    networks:
      - default
    depends_on:
      - db
    environment:
      - PGADMIN_NAME=${PGADMIN_NAME}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

    ports:
      - "5050:5050"

  scrapyd:
    container_name: hawksense-scrapyd
    build:
      context: .
      dockerfile: scrapyd.dockerfile
    ports:
      - "6800:6800"
    volumes:
      - ./scrapyd-data:/var/lib/scrapyd
      - /usr/local/lib/python3.7/dist-packages
    depends_on:
      - db
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_DRIVERNAME=${DATABASE_DRIVERNAME}
    restart: unless-stopped
