# docker-compose up --build --no-cache
# docker-compose up --build --force-recreate -d scrapyrt
# cli docker exec -it b30c070f10e0 bash
# alembic stamp head
# alembic revision --autogenerate -m "comment"
version: "3.3"

services:
  db:
    container_name: "${POSTGRES_SERVER}"
    image: library/postgres:11
    env_file:
      - .env
    environment:
      POSTGRES_DATABASE: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./scripts/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
  pgadmin:
    container_name: "${PGADMIN_NAME}"
    image: dpage/pgadmin4
    networks:
      - default
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"

  scrapyrt:
    container_name: "${SCRAPYRT_NAME}"
    env_file:
      - .env
    build:
      context: .
      dockerfile: scrapyrt.dockerfile
    command: scrapyrt -i 0.0.0.0 -p 9080
    ports:
      - "9080:9080"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: unless-stopped

#networks: for custom config
volumes:
  database-data: # named volumes can be managed easier using docker-compose
